Repository Terasology/MetalRenegades, pull requests merged in 2021-07, with the labels that each got.

#152 fix: stop discoverables and the player from spawning underwater
  src/main/java/org/terasology/metalrenegades/world/dynamic/DynamicWorldGenerator.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/discoverables/DiscoverablesProvider.java
Labels: Topic: WorldGen, Type: Bug

#151 fix: new river curve with consistent width
  src/main/java/org/terasology/metalrenegades/world/rivers/RiverToElevationProvider.java
Labels: Topic: WorldGen, Type: Improvement

#153 fix(minimap): reduce log spam of inactive entities
  src/main/java/org/terasology/metalrenegades/minimap/CharacterOverlay.java
Labels: Topic: Stabilization, Type: Bug

#150 feat: rock strata in rocky biome
  module.txt
  src/main/java/org/terasology/metalrenegades/world/dynamic/BaseBiomeProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/MRBiome.java
Labels: Topic: WorldGen, Type: Improvement

#154 fix: move block caching to Biome.initialize
  src/main/java/org/terasology/metalrenegades/world/dynamic/MRBiome.java
Labels: Topic: WorldGen, Type: Bug

#157 fix: clamp steepness to avoid inverted rivers
  src/main/java/org/terasology/metalrenegades/world/rivers/RiverToElevationProvider.java
Labels: Type: Bug

#158 feat: add world preview colors for new biomes
  src/main/java/org/terasology/metalrenegades/world/dynamic/MRBiomeFacetLayer.java
Labels: Topic: WorldGen, Type: Improvement

#155 feat: variable-size mesas based on noise
  src/main/java/org/terasology/metalrenegades/world/SimplexHillsAndMountainsProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/BaseBiomeProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/HumidityProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/MRBiome.java
  src/main/java/org/terasology/metalrenegades/world/rivers/RiverProvider.java
  src/main/java/org/terasology/metalrenegades/world/rivers/RiverToElevationProvider.java
Labels: Topic: WorldGen, Type: Improvement

#159 feat: shallower or completely dry rivers in drier areas
  src/main/java/org/terasology/metalrenegades/world/rivers/RiverToElevationProvider.java
Labels: Topic: WorldGen, Type: Improvement
