Repository Terasology/MetalRenegades, pull requests merged in 2021-09, with the labels that each got.

#169 style: fix all remaining Checkstyle warnings
  src/main/java/org/terasology/metalrenegades/PlayerInventorySystem.java
  src/main/java/org/terasology/metalrenegades/ai/actions/CheckNeedAction.java
  src/main/java/org/terasology/metalrenegades/ai/actions/SimpleComponentTargetAction.java
  src/main/java/org/terasology/metalrenegades/combat/system/EnemySpawnSystem.java
  src/main/java/org/terasology/metalrenegades/economy/events/MarketScreenRequestEvent.java
  src/main/java/org/terasology/metalrenegades/economy/events/TradeResponse.java
  src/main/java/org/terasology/metalrenegades/economy/systems/MarketManagementSystem.java
  src/main/java/org/terasology/metalrenegades/economy/systems/TradingSystem.java
  src/main/java/org/terasology/metalrenegades/economy/ui/MarketItemRegistry.java
  src/main/java/org/terasology/metalrenegades/economy/ui/MarketUISystem.java
  src/main/java/org/terasology/metalrenegades/economy/ui/TradingScreen.java
  src/main/java/org/terasology/metalrenegades/economy/ui/TradingUISystem.java
  src/main/java/org/terasology/metalrenegades/interaction/systems/WellWaterSystem.java
  src/main/java/org/terasology/metalrenegades/minimap/CharacterOverlay.java
  src/main/java/org/terasology/metalrenegades/quests/FetchQuestSystem.java
  src/main/java/org/terasology/metalrenegades/quests/TaskOverlay.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/HumidityProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/SurfaceProvider.java
  src/main/java/org/terasology/metalrenegades/world/dynamic/discoverables/ChestFillingSystem.java
Labels: Type: Chore

#170 fix: correctly reference MeshAnimations in enemyGooey.prefab
  assets/prefabs/characters/enemyGooey.prefab
Labels: Type: Bug

#171 chore: reduce max number of enemies
  src/main/java/org/terasology/metalrenegades/combat/system/EnemySpawnSystem.java
Labels: Category: Gameplay Content, Type: Chore, Topic: UI/UX
